backend:
  name: github
  repo: maxwellvolz/intervolzdotcom
  branch: master

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    extension: 'mdx'
    format: 'frontmatter'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'date', label: 'Date', widget: 'datetime' }

      - label: 'Cover Image'
        name: 'cover'
        widget: 'image'
        required: false
        hint: 'Optional cover image for blog index'

      - { name: 'pinned', label: 'Pinned', widget: 'boolean', default: false, required: false }
      - { name: 'draft', label: 'Draft', widget: 'boolean', default: false, required: false }
      - { name: 'work', label: 'Work', widget: 'boolean', default: false, required: false }
      - { label: 'Tags',name: 'tags',widget: 'string' }

      - { name: 'body', label: 'Body', widget: 'markdown' }
